### ISSUE TITLE
Show status of checks

### ISSUE THREAD

**Issue by henrik432** [xalvarez/github-team-dashboard#106]
**Is your feature request related to a problem? Please describe.**
See whether the checks (e.g. GitHub Actions) for a PR have passed or failed

**Describe the solution you'd like**
Show the status of the checks somewhere in the dashboard to see immediately if all checks have passed or some have failed.

**Comment by xalvarez** [comment]
Sounds good, feel free to make a suggestion about how should it look like.

**Comment by xalvarez** [comment]
I had an idea, I'll try it within the next few days.

Basically I want to use colours for the rows. I haven't decided yet if I want to use the colours for status checks or for reviews. Another column would be too much. I'll try both and see what works better. I'll also use some kind of colour to display drafts.
