### ISSUE TITLE
Show if a PR has already been reviewed

### ISSUE THREAD

**Issue by HenrikHoreis4321** [xalvarez/github-team-dashboard#76]
**Is your feature request related to a problem? Please describe.**
You can't see whether a PR was already reviewed by a team member

**Describe the solution you'd like**
It would be nice if the dashboard could show if a PR was approved or reviewed.

**Comment by xalvarez** [comment]
Sounds good. This feature should also show if changes have been requested.

**Comment by xalvarez** [comment]
@HenrikHoreis4321 what should be the expected behaviour? A pull request may have multiple reviews.

The following is a sample query obtaining the first 10 reviews for each PR:
```
{
  organization(login: "<example_organization>") {
    team(slug: "<example_team>") {
      repositories(first: 100, orderBy: {field: NAME, direction: ASC}) {
        nodes {
          name
          pullRequests(states: [OPEN], first: 100) {
            nodes {
              url
              createdAt
              author {
                login
              }
              title
              reviews(first: 10) {
                nodes {
                  state
                }
              }
            }
          }
        }
      }
    }
  }
}
```
